# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jsite?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 

  data:
    redis:
      host: localhost
      port: 6379
      password: Redis840@passwd
      database: 0

# 日志级别
logging:
  level:
    com.jsite: debug
